name: agradiance_flutter_kits
description: "AGRadiance Flutter Kits"
version: 0.0.2
homepage:
repository: https://github.com/agradiance/agradiance_flutter_kits

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.8
  jiffy: ^6.4.4
  flutter_form_builder: ^10.2.0
  lite_validator: ^0.0.4
  responsive_framework: ^1.5.1
  # flutter_tts: ^4.2.3
  share_plus: ^12.0.1
  dio: ^5.9.0
  http_status: ^3.3.3
  flutter_local_notifications: ^19.5.0
  collection: ^1.19.1
  image_picker: ^1.2.1
  file_picker: ^10.3.8
  file_saver: ^0.3.1
  device_info_plus: ^12.3.0
  country_picker: ^2.0.27
  # google_mobile_ads: ^6.0.0
  app_links: ^7.0.0
  permission_handler: ^12.0.1
  flutter_secure_storage: ^10.0.0
  # new_version_plus: ^1.0.1
  new_version_plus: ^0.1.2
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.3
  readmore: ^3.0.0
  dart_jsonwebtoken: ^3.3.1
  # dart_jsonwebtoken: ^3.3.1
  dlibphonenumber: ^1.1.54
  # encrypt: ^5.0.3
  encrypter_plus: ^5.1.0
  loading_animation_widget: ^1.3.0
  skeletonizer: ^2.1.2
  cached_network_image: ^3.4.1
  extended_image: ^10.0.1
  visibility_detector: ^0.4.0+2
  elegant_theme: ^0.2.4
  toastification: ^3.0.3
  # firebase_messaging: ^16.0.0
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/icon/